on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: Atime-Versions

jobs:
  Atime-Versions:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
    steps:
      - uses: SiyaoIsHiding/R_GA_GSOC@v0.0.21
